apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: postgresql-<your-initials>-pvc
 labels:
   billingType: hourly
   region: eu-de
   zone: fra02
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 5Gi
 storageClassName: ibmc-file-silver