apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: dev-mn
spec:
  selector:
    app: postgresql
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
